# Listen address
listen: "[303:c771:1561:ed81::1]:53"

# Zones are handled from top to bottom
# If zone prefix is unset, this zone it will not convert A records to ygg-prefixed AAAA
zones:
  my-direct-zone:
    domains:                        # Zone domains filter
      - "www.google.com"
      - "com.tr"
    return-public-ipv4: true        # Return 'white' A records
  default:
    domains:                        # Zone domains filter
      - "."
    prefix: "300:dada:feda:f123:ff::" # If prefix is set, then it will convert A records to AAAA
    return-public-ipv4: false       # Return 'white' A records

# What to do with an "0.0.0.0" and [::] addresses
#   "ignore"  - treated like a regular address (i.e. 0.0.0.0 return as [prefix::], [::] - drop)
#               default behavior.
#   "process" - 0.0.0.0 translate to [::]. [::] return "as-is"
#   "discard" - discard this address
invalid-address: ignore

# Forwarders
forwarders:
  ".ygg": "[308:84:68:55::]:53"  # Alfis servers: 308:25:40:bd:: / 308:62:45:62:: / 308:c8:48:45::

# Default DNS forwarder
default: 8.8.8.8:53

# Static addresses
static:
  "test.com" : 8.8.8.8
  "test2.com" : 8.8.8.8

# Cache timers. In minutes
cache:
    expiration: 5
    purge: 10